BUCKET_NAME = 'proag-data'
TYPE_DATA_MODELS = 'models'
TYPE_DATA_COH = 'data/coh_stats'
TYPE_DATA_INDX = 'data/s2_stats'
TYPE_DATA_GEOJSON = 'data/geojson'
TYPE_DATA_PREPROCES = 'data/preproces_fill'
RESULTS_MODEL ='output/model_results'
FINAL_RESULTS ='output/final_results'
PATH_PREFIX_MODELS = 'planting-dates/pd-models-2024/stats-v2'
PATH_PREFIX_DATA_COH = 'planting-dates/pd-data-2023-2024/PA23predictionML_1_3to9_7_rawCOH/'
PATH_PREFIX_DATA_INDX = 'planting-dates/pd-data-2023-2024/PA23predictionML1_3to9_7_raw/'
PATH_PREFIX_DATA_GEOJSON = 'planting-dates/pd-data-2023-2024/'
STR_CONN_DEV = 'mongodb+srv://cluster1.gmxcy.mongodb.net/?authSource=%24external&authMechanism=MONGODB-AWS'
DB_NAME = 'algo_results_dev'
COLL_NAME = 'planting_dates_2024'